### ISSUE TITLE
Extraction of Halo2 in specs is broken for Coq

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#158]

**Comment by cmester0** [comment]
Should be fixed by #160.

**Comment by W95Psp** [comment]
Just checked on main, this is still broken, I get the following errors:

```
error[HAX0001]: (Coq backend) something is not implemented yet.
                [expr] node app global vcar projector tuple
    --> halo2/src/halo2.rs:5509:19
     |
5509 |         let p_x = point.0;
     |                   ^^^^^^^

error[HAX0001]: (Coq backend) something is not implemented yet.
                [expr] node app global vcar projector tuple
    --> halo2/src/halo2.rs:5485:26
     |
5485 |         let y: FpVesta = points[i].1;
     |                          ^^^^^^^^^^^

error[HAX0001]: (Coq backend) something is not implemented yet.
                [expr] node app global vcar projector tuple
    --> halo2/src/halo2.rs:5484:26
     |
5484 |         let x: FpVesta = points[i].0;
     |                          ^^^^^^^^^^^
```
