### ISSUE TITLE
Default method in trait blocks

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#624]

**Comment by W95Psp** [comment]
Was fixed by https://github.com/hacspec/hax/pull/824

**Comment by chrysn** [comment]
I'm still getting an error when running the latest hax version on the latest [lakers](https://github.com/openwsn-berkeley/lakers) main:

```
error: [HAX0008] (reject_TraitItemDefault) ExplicitRejection { reason: "a node of kind [Trait_item_default] have been found in the AST" }
  --> shared/src/crypto.rs:41:5
   |
41 |       fn supported_suites(&self) -> EdhocBuffer<MAX_SUITES_LEN> {
   |  _____^
42 | |         EdhocBuffer::<MAX_SUITES_LEN>::new_from_slice(&[EDHOCSuite::CipherSuite2 as u8])
43 | |             .expect("This should never fail, as the slice is of the correct length")
44 | |     }
   | |_____^
   |
```

Is this a regression on this issue, or is this a new one?

<details><summary><tt>cargo-hax --version</tt></summary>

```
hax 
version=0.3.1
commit=unknown
```

(built from 6254bb38f5dbb4c9459a13ccc82070bc4e98da4c)

</details>
